version: "3.9"

services:

  node-express:
    build: .
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "4501:4500"
    volumes:
      - .:/app
    command: npm run dev
    networks:
      - postgres-cluster

networks:
  postgres-cluster:
    external: true
